compatibility_date = "2022-07-31"
main = "src/index.ts"
name = "avatar-upload"

node_compat = true

[vars]
BASE_WEB3_ENDPOINT = "http://localhost:8545"
REGISTRY_ADDRESS = "0x3B02fF1e626Ed7a8fd6eC5299e2C54e1421B626B"
SUPPORTED_NETWORKS = ["mainnet", "local"]
WRAPPER_ADDRESS = '{ "mainnet": "", "local": "0xB7aa4c318000BB9bD16108F81C40D02E48af1C42" }'

[[r2_buckets]]
binding = "AVATAR_BUCKET"
bucket_name = 'avatar-storage'
preview_bucket_name = 'preview-avatar-storage'
